using FluentValidation;
using FluentValidation.AspNetCore;
using Hope.Application.Authentication.Commands.Register;
using Hope.Application.Common.Behaviors;
using Hope.Infrastructure;
using MediatR;
using Microsoft.OpenApi.Models;
using System.Globalization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;
using Hope.Infrastructure.Persistence;
using CloudinaryDotNet;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSingleton(new Cloudinary(new Account(
    "dmijfuun4",
    "879857692416225",
    "znf_0MgUCA9cg9-FxkdTrcugb7M"
)));

builder.Services.AddCors(options =>
{
    options.AddPolicy("CorsPolicy", builder =>
    {
        builder.AllowAnyOrigin();
        builder.AllowAnyMethod();
        builder.AllowAnyHeader();

    });
});

// Add localization services
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");

builder.Services.Configure<RequestLocalizationOptions>(options =>
{
    var supportedCultures = new[]
    {
        new CultureInfo("en"),
        new CultureInfo("ar")
    };

    options.DefaultRequestCulture = new RequestCulture("en");
    options.SupportedCultures = supportedCultures;
    options.SupportedUICultures = supportedCultures;
});

//================== Swagger =====================================
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1",
                 new OpenApiInfo
                 {
                     Title = "Hope API",
                     Description = "API For Hope Project",
                     Version = "v1",
                     TermsOfService = null
                 });
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "JWT Authorization header using the Bearer scheme."
    });
    options.AddSecurityRequirement(new OpenApiSecurityRequirement()
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });

    //Locate the XML file being generated by ASP.NET...
    foreach (var name in Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.AllDirectories).Distinct().Where(x => x.Contains("Hope.Api.xml")))
    {
        options.IncludeXmlComments(filePath: name);
    }

});

// Add Infrastructure services
builder.Services.AddInfrastructure(builder.Configuration);
// Add this line in your service registration
builder.Services.AddHttpContextAccessor();
// Add MediatR
builder.Services.AddMediatR(cfg => {
    cfg.RegisterServicesFromAssembly(typeof(RegisterCommand).Assembly);
    cfg.AddBehavior(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));
});

// Add FluentValidation
builder.Services.AddFluentValidationAutoValidation(config => {
    config.DisableDataAnnotationsValidation = true;
});
builder.Services.AddValidatorsFromAssemblyContaining<RegisterCommandValidator>();


var app = builder.Build();

//// Configure the HTTP request pipeline
//if (app.Environment.IsDevelopment())
//{
    app.UseSwagger();
    app.UseSwaggerUI();
//}
app.UseStaticFiles();
app.UseHttpsRedirection();
app.UseCors("CorsPolicy");
// Add request localization middleware
app.UseRequestLocalization();

// Add exception handling middleware
app.UseMiddleware<Hope.Api.Middleware.ExceptionHandlingMiddleware>();



app.UseAuthentication();
app.UseAuthorization();

using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        // Make sure to await this call
        await ApplicationDbContextSeed.SeedDefaultUserAsync(services, app.Configuration);
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogInformation("Database seeding completed successfully.");
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "An error occurred while seeding the database.");
    }
}

app.MapControllers();

app.Run();

